
 export   const carmakes = [
        {"value": "AC", "id": 1},
        {"value": "Acura", "id": 2},
        {"value": "Adler", "id": 3},
        {"value": "Alfa Romeo", "id": 4},
        {"value": "Alpina", "id": 5},
        {"value": "Alpine", "id": 6},
        {"value": "AM General", "id": 7},
        {"value": "AMC", "id": 8},
        {"value": "Ariel", "id": 9},
        {"value": "Aro", "id": 10},
        {"value": "Asia", "id": 11},
        {"value": "Aston Martin", "id": 12},
        {"value": "Audi", "id": 13},
        {"value": "Aurus", "id": 14},
        {"value": "Austin", "id": 15},
        {"value": "Austin Healey", "id": 16},
        {"value": "Autobianchi", "id": 17},
        {"value": "BAIC", "id": 18},
        {"value": "Bajaj", "id": 19},
        {"value": "Baltijas Dzips", "id": 20},
        {"value": "Batmobile", "id": 21},
        {"value": "Bentley", "id": 22},
        {"value": "Bertone", "id": 23},
        {"value": "Bilenkin", "id": 24},
        {"value": "Bitter", "id": 25},
        {"value": "BMW", "id": 26},
        {"value": "Borgward", "id": 27},
        {"value": "Brabus", "id": 28},
        {"value": "Brilliance", "id": 29},
        {"value": "Bristol", "id": 30},
        {"value": "Bufori", "id": 31},
        {"value": "Bugatti", "id": 32},
        {"value": "Buick", "id": 33},
        {"value": "BYD", "id": 34},
        {"value": "Byvin", "id": 35},
        {"value": "Cadillac", "id": 36},
        {"value": "Callaway", "id": 37},
        {"value": "Carbodies", "id": 38},
        {"value": "Caterham", "id": 39},
        {"value": "Chana", "id": 40},
        {"value": "Changan", "id": 41},
        {"value": "ChangFeng", "id": 42},
        {"value": "Changhe", "id": 43},
        {"value": "Chery", "id": 44},
        {"value": "Chevrolet", "id": 45},
        {"value": "Chrysler", "id": 46},
        {"value": "Citroen", "id": 47},
        {"value": "Cizeta", "id": 48},
        {"value": "Coggiola", "id": 49},
        {"value": "Cord", "id": 50},
        {"value": "Dacia", "id": 51},
        {"value": "Dadi", "id": 52},
        {"value": "Daewoo", "id": 53},
        {"value": "Daihatsu", "id": 54},
        {"value": "Daimler", "id": 55},
        {"value": "Datsun", "id": 56},
        {"value": "De Tomaso", "id": 57},
        {"value": "Delage", "id": 58},
        {"value": "DeLorean", "id": 59},
        {"value": "Derways", "id": 60},
        {"value": "DeSoto", "id": 61},
        {"value": "Dodge", "id": 62},
        {"value": "DongFeng", "id": 63},
        {"value": "Doninvest", "id": 64},
        {"value": "Donkervoort", "id": 65},
        {"value": "DS", "id": 66},
        {"value": "DW Hower", "id": 67},
        {"value": "E-Car", "id": 68},
        {"value": "Eagle", "id": 69},
        {"value": "Eagle Cars", "id": 70},
        {"value": "Excalibur", "id": 71},
        {"value": "FAW", "id": 72},
        {"value": "Ferrari", "id": 73},
        {"value": "Fiat", "id": 74},
        {"value": "Fisker", "id": 75},
        {"value": "Flanker", "id": 76},
        {"value": "Ford", "id": 77},
        {"value": "Foton", "id": 78},
        {"value": "FSO", "id": 79},
        {"value": "Fuqi", "id": 80},
        {"value": "GAC", "id": 81},
        {"value": "Geely", "id": 82},
        {"value": "Genesis", "id": 83},
        {"value": "Geo", "id": 84},
        {"value": "GMC", "id": 85},
        {"value": "Gonow", "id": 86},
        {"value": "Gordon", "id": 87},
        {"value": "GP", "id": 88},
        {"value": "Great Wall", "id": 89},
        {"value": "Hafei", "id": 90},
        {"value": "Haima", "id": 91},
        {"value": "Hanomag", "id": 92},
        {"value": "Haval", "id": 93},
        {"value": "Hawtai", "id": 94},
        {"value": "Hindustan", "id": 95},
        {"value": "Hispano-Suiza", "id": 96},
        {"value": "Holden", "id": 97},
        {"value": "Honda", "id": 98},
        {"value": "Horch", "id": 99},
        {"value": "HuangHai", "id": 100},
        {"value": "Hudson", "id": 101},
        {"value": "Hummer", "id": 102},
        {"value": "Hyundai", "id": 103},
        {"value": "Infiniti", "id": 104},
        {"value": "Innocenti", "id": 105},
        {"value": "Invicta", "id": 106},
        {"value": "Iran Khodro", "id": 107},
        {"value": "Isdera", "id": 108},
        {"value": "Isuzu", "id": 109},
        {"value": "JAC", "id": 110},
        {"value": "Jaguar", "id": 111},
        {"value": "Jeep", "id": 112},
        {"value": "Jensen", "id": 113},
        {"value": "Jinbei", "id": 114},
        {"value": "JMC", "id": 115},
        {"value": "Kia", "id": 116},
        {"value": "Koenigsegg", "id": 117},
        {"value": "KTM AG", "id": 118},
        {"value": "LADA (ВАЗ)", "id": 119},
        {"value": "Lamborghini", "id": 120},
        {"value": "Lancia", "id": 121},
        {"value": "Land Rover", "id": 122},
        {"value": "Landwind", "id": 123},
        {"value": "Lexus", "id": 124},
        {"value": "Liebao Motor", "id": 125},
        {"value": "Lifan", "id": 126},
        {"value": "Ligier", "id": 127},
        {"value": "Lincoln", "id": 128},
        {"value": "Lotus", "id": 129},
        {"value": "LTI", "id": 130},
        {"value": "Lucid", "id": 131},
        {"value": "Luxgen", "id": 132},
        {"value": "Mahindra", "id": 133},
        {"value": "Marcos", "id": 134},
        {"value": "Marlin", "id": 135},
        {"value": "Marussia", "id": 136},
        {"value": "Maruti", "id": 137},
        {"value": "Maserati", "id": 138},
        {"value": "Maybach", "id": 139},
        {"value": "Mazda", "id": 140},
        {"value": "McLaren", "id": 141},
        {"value": "Mega", "id": 142},
        {"value": "Mercedes-Benz", "id": 143},
        {"value": "Mercury", "id": 144},
        {"value": "Metrocab", "id": 145},
        {"value": "MG", "id": 146},
        {"value": "Microcar", "id": 147},
        {"value": "Minelli", "id": 148},
        {"value": "MINI", "id": 149},
        {"value": "Mitsubishi", "id": 150},
        {"value": "Mitsuoka", "id": 151},
        {"value": "Morgan", "id": 152},
        {"value": "Morris", "id": 153},
        {"value": "Nash", "id": 154},
        {"value": "Nissan", "id": 155},
        {"value": "Noble", "id": 156},
        {"value": "Oldsmobile", "id": 157},
        {"value": "Opel", "id": 158},
        {"value": "Osca", "id": 159},
        {"value": "Packard", "id": 160},
        {"value": "Pagani", "id": 161},
        {"value": "Panoz", "id": 162},
        {"value": "Perodua", "id": 163},
        {"value": "Peugeot", "id": 164},
        {"value": "PGO", "id": 165},
        {"value": "Piaggio", "id": 166},
        {"value": "Plymouth", "id": 167},
        {"value": "Pontiac", "id": 168},
        {"value": "Porsche", "id": 169},
        {"value": "Premier", "id": 170},
        {"value": "Proton", "id": 171},
        {"value": "PUCH", "id": 172},
        {"value": "Puma", "id": 173},
        {"value": "Qoros", "id": 174},
        {"value": "Qvale", "id": 175},
        {"value": "Rambler", "id": 176},
        {"value": "Ravon", "id": 177},
        {"value": "Reliant", "id": 178},
        {"value": "Renaissance", "id": 179},
        {"value": "Renault", "id": 180},
        {"value": "Renault Samsung", "id": 181},
        {"value": "Rezvani", "id": 182},
        {"value": "Rimac", "id": 183},
        {"value": "Rolls-Royce", "id": 184},
        {"value": "Ronart", "id": 185},
        {"value": "Rover", "id": 186},
        {"value": "Saab", "id": 187},
        {"value": "Saipa", "id": 188},
        {"value": "Saleen", "id": 189},
        {"value": "Santana", "id": 190},
        {"value": "Saturn", "id": 191},
        {"value": "Scion", "id": 192},
        {"value": "SEAT", "id": 193},
        {"value": "Shanghai Maple", "id": 194},
        {"value": "ShuangHuan", "id": 195},
        {"value": "Simca", "id": 196},
        {"value": "Skoda", "id": 197},
        {"value": "Smart", "id": 198},
        {"value": "Soueast", "id": 199},
        {"value": "Spectre", "id": 200},
        {"value": "Spyker", "id": 201},
        {"value": "SsangYong", "id": 202},
        {"value": "Steyr", "id": 203},
        {"value": "Studebaker", "id": 204},
        {"value": "Subaru", "id": 205},
        {"value": "Suzuki", "id": 206},
        {"value": "Talbot", "id": 207},
        {"value": "TATA", "id": 208},
        {"value": "Tatra", "id": 209},
        {"value": "Tazzari", "id": 210},
        {"value": "Tesla", "id": 211},
        {"value": "Think", "id": 212},
        {"value": "Tianma", "id": 213},
        {"value": "Tianye", "id": 214},
        {"value": "Tofas", "id": 215},
        {"value": "Toyota", "id": 216},
        {"value": "Trabant", "id": 217},
        {"value": "Tramontana", "id": 218},
        {"value": "Triumph", "id": 219},
        {"value": "TVR", "id": 220},
        {"value": "Ultima", "id": 221},
        {"value": "Vauxhall", "id": 222},
        {"value": "Vector", "id": 223},
        {"value": "Venturi", "id": 224},
        {"value": "Volkswagen", "id": 225},
        {"value": "Volvo", "id": 226},
        {"value": "Vortex", "id": 227},
        {"value": "W Motors", "id": 228},
        {"value": "Wanderer", "id": 229},
        {"value": "Wartburg", "id": 230},
        {"value": "Westfield", "id": 231},
        {"value": "Wiesmann", "id": 232},
        {"value": "Willys", "id": 233},
        {"value": "Xin Kai", "id": 234},
        {"value": "Zastava", "id": 235},
        {"value": "Zenos", "id": 236},
        {"value": "Zenvo", "id": 237},
        {"value": "Zibar", "id": 238},
        {"value": "Zotye", "id": 239},
        {"value": "ZX", "id": 240},
        {"value": "Автокам", "id": 241},
        {"value": "ГАЗ", "id": 242},
        {"value": "Гоночный болид", "id": 243},
        {"value": "Ё-мобиль", "id": 244},
        {"value": "ЗАЗ", "id": 245},
        {"value": "ЗИЛ", "id": 246},
        {"value": "ЗиС", "id": 247},
        {"value": "ИЖ", "id": 248},
        {"value": "Канонир", "id": 249},
        {"value": "Комбат", "id": 250},
        {"value": "ЛуАЗ", "id": 251},
        {"value": "Москвич", "id": 252},
        {"value": "СМЗ", "id": 253},
        {"value": "ТагАЗ", "id": 254},
        {"value": "УАЗ", "id": 255}
    ];




